name: Docker Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t my-app .

    - name: Test environment setup
      run: |
        docker run --rm my-app fish -c "echo 'Testing fish shell'"
        docker run --rm my-app bun --version
        docker run --rm my-app node --version
        docker run --rm my-app whoami

    - name: Run application (test mode)
      run: |
        docker run --rm \
          -e OLLAMA_HOST=http://localhost \
          -e OLLAMA_PORT=11434 \
          my-app bun run start &
        sleep 10
        docker ps